#EXP3

In [ ]:
!pip install nltk
from nltk import download
download('stopwords')
download('punkt')
download('wordnet')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package wordnet to /root/nltk_data...


True

In [ ]:
# tokenization

from nltk.tokenize import word_tokenize as WT,sent_tokenize as ST,wordpunct_tokenize as WPT,TweetTokenizer as TT

sent = "The quick brown fox jumped. Over the lazy dog! #Dog#Fox"
wt_tokens = WT(sent)
st_tokens = ST(sent)
wpt_tokens = WPT(sent)
tt_tokens = TT().tokenize(sent)
print(wt_tokens)
print(st_tokens)
print(wpt_tokens)
print(tt_tokens)

['The', 'quick', 'brown', 'fox', 'jumped', '.', 'Over', 'the', 'lazy', 'dog', '!', '#', 'Dog', '#', 'Fox']
['The quick brown fox jumped.', 'Over the lazy dog!', '#Dog#Fox']
['The', 'quick', 'brown', 'fox', 'jumped', '.', 'Over', 'the', 'lazy', 'dog', '!', '#', 'Dog', '#', 'Fox']
['The', 'quick', 'brown', 'fox', 'jumped', '.', 'Over', 'the', 'lazy', 'dog', '!', '#Dog', '#Fox']


In [ ]:
# stop word removal

from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize as WT

print(stopwords.words('english'))
StopWords=stopwords.words('english')

sent = "The quick brown fox jumped. Over a lazy dog! #Dog#Fox. Dancing"
wt_tokens = WT(sent)

after_removing_stopwords = [ w for w in wt_tokens if w.lower() not in StopWords]
print(after_removing_stopwords)

['i', 'me', 'my', 'myself', 'we', 'our', 'ours', 'ourselves', 'you', "you're", "you've", "you'll", "you'd", 'your', 'yours', 'yourself', 'yourselves', 'he', 'him', 'his', 'himself', 'she', "she's", 'her', 'hers', 'herself', 'it', "it's", 'its', 'itself', 'they', 'them', 'their', 'theirs', 'themselves', 'what', 'which', 'who', 'whom', 'this', 'that', "that'll", 'these', 'those', 'am', 'is', 'are', 'was', 'were', 'be', 'been', 'being', 'have', 'has', 'had', 'having', 'do', 'does', 'did', 'doing', 'a', 'an', 'the', 'and', 'but', 'if', 'or', 'because', 'as', 'until', 'while', 'of', 'at', 'by', 'for', 'with', 'about', 'against', 'between', 'into', 'through', 'during', 'before', 'after', 'above', 'below', 'to', 'from', 'up', 'down', 'in', 'out', 'on', 'off', 'over', 'under', 'again', 'further', 'then', 'once', 'here', 'there', 'when', 'where', 'why', 'how', 'all', 'any', 'both', 'each', 'few', 'more', 'most', 'other', 'some', 'such', 'no', 'nor', 'not', 'only', 'own', 'same', 'so', 'than', '

In [ ]:
# Stemming

from nltk.stem import PorterStemmer
PS = PorterStemmer()

stemmed_tokens = [PS.stem(w) for w in after_removing_stopwords]
print(stemmed_tokens)

['quick', 'brown', 'fox', 'jump', '.', 'lazi', 'dog', '!', '#', 'dog', '#', 'fox', '.', 'danc']


In [ ]:
# lemmetization

from nltk.stem import WordNetLemmatizer
LM = WordNetLemmatizer()
lemm_words = [LM.lemmatize(w) for w in after_removing_stopwords]
print(lemm_words)

['quick', 'brown', 'fox', 'jumped', '.', 'lazy', 'dog', '!', '#', 'Dog', '#', 'Fox', '.', 'Dancing']


# EXP4

In [ ]:
# POS tagging
import spacy
nlp = spacy.load("en_core_web_sm")
sent = "The quick brown fox jumped over the lazy dog."
doc = nlp(sent)

for token in doc:
  print(f"{token.text} => {token.pos_}")

In [ ]:
# dependency parsing

import spacy
nlp = spacy.load("en_core_web_sm")
sent = "The quick brown fox jumped over the lazy dog."
doc = nlp(sent)

for token in doc :
  print(f"{token.text} {token.dep_} > {token.head.text}")

In [ ]:
#named entity recognition
import spacy

# Load English NER model
nlp = spacy.load("en_core_web_sm")

# Example text
text = "Apple is looking at buying U.K. startup for $1 billion"

# Process the text with SpaCy
doc = nlp(text)

# Extract named entities
for ent in doc.ents:
    print(ent.text, ent.label_)

In [ ]:
!pip install spacy

# EXP 5

In [ ]:
# One hot encoding
from sklearn.preprocessing import OneHotEncoder
corpus = [
    'dog bites man',
    'man bites dog',
    'dog eats meat',
    'man eats food'
]
corpus_reshaped = [[doc] for doc in corpus]

ohe = OneHotEncoder(sparse = False)
encoded = ohe.fit_transform(corpus_reshaped)
print(encoded)

[[1. 0. 0. 0.]
 [0. 0. 1. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 1.]]


/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


In [ ]:
# bag of words
from sklearn.feature_extraction.text import CountVectorizer
corpus = [
    'dog bites man',
    'man bites dog',
    'dog eats meat',
    'man eats food'
]

vec = CountVectorizer()
x=vec.fit_transform(corpus)

print(x.toarray())
print(vec.vocabulary_) # shows the indices

[[1 1 0 0 1 0]
 [1 1 0 0 1 0]
 [0 1 1 0 0 1]
 [0 0 1 1 1 0]]
{'dog': 1, 'bites': 0, 'man': 4, 'eats': 2, 'meat': 5, 'food': 3}


In [ ]:
# bag of N grams
from sklearn.feature_extraction.text import CountVectorizer
corpus = [
    'dog bites man',
    'man bites dog',
    'dog eats meat',
    'man eats food'
]

vec = CountVectorizer(ngram_range=(1,2))
x=vec.fit_transform(corpus)

print(x.toarray())
print(vec.vocabulary_) # shows the indices

[[1 0 1 1 1 0 0 0 0 0 1 0 0 0]
 [1 1 0 1 0 0 0 0 0 0 1 1 0 0]
 [0 0 0 1 0 1 1 0 1 0 0 0 0 1]
 [0 0 0 0 0 0 1 1 0 1 1 0 1 0]]
{'dog': 3, 'bites': 0, 'man': 10, 'dog bites': 4, 'bites man': 2, 'man bites': 11, 'bites dog': 1, 'eats': 6, 'meat': 13, 'dog eats': 5, 'eats meat': 8, 'food': 9, 'man eats': 12, 'eats food': 7}


In [ ]:
# TF-IDF

from sklearn.feature_extraction.text import TfidfVectorizer
corpus = [
    'dog bites man',
    'man bites dog',
    'dog eats meat',
    'man eats food'
]
tfidf = TfidfVectorizer()
x = tfidf.fit_transform(corpus)

print(x.toarray())
print(tfidf.vocabulary_)

[[0.65782931 0.53256952 0.         0.         0.53256952 0.        ]
 [0.65782931 0.53256952 0.         0.         0.53256952 0.        ]
 [0.         0.44809973 0.55349232 0.         0.         0.70203482]
 [0.         0.         0.55349232 0.70203482 0.44809973 0.        ]]
{'dog': 1, 'bites': 0, 'man': 4, 'eats': 2, 'meat': 5, 'food': 3}


In [ ]:
!pip install gensim

In [ ]:
# Word embeddings

from gensim.models import Word2Vec
import numpy as np

corpus = [
    'dog bites man',
    'man bites dog',
    'dog eats meat',
    'man eats food'
]
tokenized_corpus = [doc.split() for doc in corpus]

model = Word2Vec(sentences = tokenized_corpus ,vector_size = 100, window=5,min_count=1,workers=4)
def embeddings(doc):
  emb = [model.wv[word] for word in doc if word in model.wv]
  if emb:
    return np.mean(emb,axis=0)
  else:
    return np.zeros(model.vector_size)

x = np.array([embeddings(doc) for doc in tokenized_corpus])

print(x)

[[-5.7995315e-03  4.4005080e-03  3.3651907e-03  4.2613116e-03
   9.2253304e-04 -5.7932665e-03  3.4358669e-03  7.3200786e-03
  -5.9668423e-04 -5.8158967e-03  5.4508769e-03 -1.7435373e-03
  -2.0568350e-03  2.4716950e-03  2.3174530e-03  1.0864957e-03
   6.1673387e-03  1.0535377e-03 -6.7345961e-03 -1.0620216e-03
   3.7771116e-03 -5.4909306e-04  8.2200086e-03  1.3285212e-04
   1.1138282e-03  6.7142653e-04  9.2486465e-05  4.6797390e-03
  -2.4128084e-03  1.0685941e-03  1.0422996e-03 -3.0377072e-03
   5.9951021e-04 -5.0345589e-03  1.8136505e-03  3.2225230e-03
   8.0758883e-03 -1.9352456e-03  6.0329461e-05  4.7613536e-03
   5.7476730e-04  1.0613020e-03 -3.8777019e-03 -2.5172802e-03
   1.3959208e-03  3.4761357e-03  3.8277949e-04  1.8962369e-03
   1.1215905e-03  2.8843472e-03  1.3120301e-03 -1.6461100e-03
  -4.6422952e-03 -1.7906037e-03  4.7048461e-04  1.2636752e-03
   5.1752334e-03  3.0605046e-03  4.4141375e-04  4.2727385e-03
  -3.2778904e-03  2.8309457e-03 -3.6010580e-04 -4.6386220e-03
   2.135

# EXP2

In [ ]:
#NLTK
import nltk
from nltk.tokenize import word_tokenize as WT

sent="hello how are you doing and what do you do"
nltk.download('punkt')
tokens=WT(sent)
print(tokens)

In [ ]:
#TEXTBLOB
from textblob import TextBlob
text="I love using this product. It's fantastic!"
blob=TextBlob(text)
sentiment=blob.sentiment.polarity
print(sentiment)

In [ ]:
!pip install flair

In [ ]:
#FLAIR
from flair.data import Sentence
from flair.models import SequenceTagger

# Load NER model
tagger = SequenceTagger.load('ner')

# Example text
text = "Flair is a simple and powerful NLP library."

# Tokenize the text
sentence = Sentence(text)

# Tag the text with NER
tagger.predict(sentence)

# Get named entities
for entity in sentence.get_spans('ner'):
    print(entity)

2024-04-15 05:37:50,115 SequenceTagger predicts: Dictionary with 20 tags: <unk>, O, S-ORG, S-MISC, B-PER, E-PER, S-LOC, B-ORG, E-ORG, I-PER, S-PER, B-MISC, I-MISC, E-MISC, I-ORG, B-LOC, E-LOC, I-LOC, <START>, <STOP>
Span[0:1]: "Flair" → ORG (0.2899)
Span[6:7]: "NLP" → MISC (0.6945)


In [ ]:
#SPACY
import spacy
nlp=spacy.load("en_core_web_sm")
sent="a quick brown fox jumped.Over the lazy dog."
doc=nlp(sent)

for token in doc:
  print(f"{token.text}=>{token.pos_}")

a=>DET
quick=>ADJ
brown=>ADJ
fox=>NOUN
jumped=>VERB
.=>PUNCT
Over=>ADP
the=>DET
lazy=>ADJ
dog=>NOUN
.=>PUNCT


In [ ]:
#SKLEARN
from sklearn.feature_extraction.text import CountVectorizer
corpus=[
    'dog bites man',
    'man bites dog',
    'dog eats meat',
    'man eats food'
]
vec=CountVectorizer()
x=vec.fit_transform(corpus)

print(x.toarray())
print(vec.vocabulary_)